const data = {
    products: [
        {
            name: 'Брюки',
            slug: 'pants-o-stin-002',
            tags: 'брюки',
            price: 2499,
            raiting: 10,
            brand: 'O\'stin',
            image: '/images/ff10c940dd1be0d2a6bb0c123e058515.jpg',
            url: '',
            instock: 345,
            gender: 'women',
            category: 'брюки',
            season: 'Осень-зима',
            color: 'бежевый',
            size: 36,
            shop: 'O\'stin',
            description: 'Акция',
            discount: 0,
            featured: false,
            edited: false,
            date: '',
        },
        {
            name: 'Черные джоггеры узкого кроя с полосой по бокам',
            slug: 'chernie-joggeri-uzkogo-kroya-topshop-003',
            brand: 'Topshop',
            price: 2290,
            raiting: 15,
            image: '/images/60a5f31d1631c0e1e3cd2284019a0383.jpg',
            instock: 345,
            gender: 'women',
            category: 'брюки',
            season: 'На каждый день',
            color: 'Черный',
            size: 36,
            shop: 'Topshop',
            description: 'Акция',
            discount: 26,
        },
        {
            name: 'СВОБОДНЫЕ БРЮКИ-ЧИНОСЫ ИЗ ОРГАНИЧЕСКОГО ХЛОПКА',
            slug: 'svobodnie-bruki-chinos-cos-004',
            price: 7890,
            raiting: 10,
            brand: 'Cos',
            image: '/images/9f795d47a483ce780a6d16dde2639fc0.jpg',
            instock: 345,
            gender: 'women',
            category: 'брюки',
            season: 'На каждый день',
            color: '',
            size: 36,
            shop: 'Cos',
            description: 'Акция',
            discount: 0,
        },
        {
            name: 'Брюки',
            slug: 'bruki-sela-005',
            price: 4499,
            raiting: 10,
            brand: 'Sela',
            image: '/images/ff10c940dd1be0d2a6bb0c123e058515.jpg',
            instock: 345,
            gender: 'women',
            category: 'брюки',
            season: 'Осень-зима',
            color: 'белый',
            size: 36,
            shop: 'Sela',
            description: 'Акция',
            discount: 33,
        },
        {
            name: 'Брюки',
            slug: 'bruki-madeleine-006',
            price: 10790,
            raiting: 10,
            brand: 'Madeleine',
            image: '/images/c437a3139315a4b66dee63f414e2475a.jpg',
            instock: 345,
            gender: 'women',
            category: 'брюки',
            season: 'Весна-лето',
            color: 'черный',
            size: 36,
            shop: 'Madeleine',
            description: 'Акция',
            discount: 10,
        },
        {
            name: 'Брюки',
            slug: 'pants-o-stin-007',
            price: 2499,
            raiting: 10,
            brand: 'O\'stin',
            image: '/images/ff10c940dd1be0d2a6bb0c123e058515.jpg',
            instock: 345,
            gender: 'women',
            category: 'брюки',
            season: 'Осень-зима',
            color: 'бежевый',
            size: 36,
            shop: 'O\'stin',
            description: 'Акция',
            discount: 0,
        },
        {
            name: 'Брюки',
            slug: 'pants-o-stin-008',
            price: 2499,
            raiting: 10,
            brand: 'O\'stin',
            image: '/images/ff10c940dd1be0d2a6bb0c123e058515.jpg',
            instock: 345,
            gender: 'women',
            category: 'брюки',
            season: 'Осень-зима',
            color: 'бежевый',
            size: 36,
            shop: 'O\'stin',
            description: 'Акция',
            discount: 0,
        },
        {
            name: 'Брюки',
            slug: 'pants-o-stin-009',
            price: 2499,
            raiting: 10,
            brand: 'O\'stin',
            image: '/images/ff10c940dd1be0d2a6bb0c123e058515.jpg',
            instock: 345,
            gender: 'women',
            category: 'брюки',
            season: 'Осень-зима',
            color: 'бежевый',
            size: 36,
            shop: 'O\'stin',
            description: 'Акция',
            discount: 0,
        },

    ]
}

export default data